name: Pet

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/2 * * * *'
    # - cron:  '0 */12 * * *'

jobs:
  pet:
    env:
      PRIVATE_KEY: ${{ secrets.PrivateKey }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: node index.js
